# -*- coding: utf-8 -*-
"""sentiment_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1olI2xSvZgS3OQi_FOy4WtGsN7ZTxPtdC
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile sentiment_model.py
# 
# import re
# from textblob import TextBlob
# 
# def clean_text(text):
#     text = text.lower()
#     text = re.sub(r'[^a-zA-Z\s]', '', text)
#     return text
# 
# def predict_sentiment(review):
#     review = clean_text(review)
#     polarity = TextBlob(review).sentiment.polarity
# 
#     if polarity > 0:
#         return "Positive 😊"
#     elif polarity < 0:
#         return "Negative 😠"
#     else:
#         return "Neutral 😐"
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# from sentiment_model import predict_sentiment
# 
# st.set_page_config(
#     page_title="Swiggy Review Sentiment Analysis",
#     page_icon="🍔",
#     layout="centered"
# )
# 
# st.title("🍔 Swiggy Review Sentiment Analysis")
# st.write("Analyze customer reviews using NLP")
# 
# review = st.text_area("Enter a Swiggy Review")
# 
# if st.button("Analyze Sentiment"):
#     if review.strip() == "":
#         st.warning("Please enter a review")
#     else:
#         sentiment = predict_sentiment(review)
#         st.success(f"Sentiment: {sentiment}")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# streamlit
# textblob
#

import os
os.listdir()